#!/bin/bash

set -e

if [ ! -d software ]; then
    tar xzf software.tar.gz
fi

if [ "x$TMPDIR_OVERRIDE" != "x" ]; then
   export TMPDIR="$TMPDIR_OVERRIDE"
fi
if [ "x$TMPDIR" = "x" ]; then
   export TMPDIR=/tmp
fi
if [ ! -e "$TMPDIR" ]; then
    mkdir -p $TMPDIR
fi

# TACC Hack
export PATH=/scratch/projects/xsede/jdk64/jdk1.8.0_25/bin:$PATH
echo
echo "Java used is" `which java`
echo

java -Djava.io.tmpdir=$TMPDIR -Xmx17g -XX:+UseSerialGC -jar ./software/picard-tools-1.92/"$@"

